### ISSUE TITLE
methdiff.py Report errors

### ISSUE THREAD

**Issue by ttian627** [genome-vendor/bsmap#6]
Traceback (most recent call last):
  File "../../tools/bsmap-2.90/methdiff.py", line 133, in <module>
    cmp_chrom(cr)
  File "../../tools/bsmap-2.90/methdiff.py", line 112, in cmp_chrom
    pval = get_pval(m[0], d[0], m[1], d[1])
  File "../../tools/bsmap-2.90/methdiff.py", line 86, in get_pval
    l0, u0 = conf_intv(m0, d0, z0)
  File "../../tools/bsmap-2.90/methdiff.py", line 81, in conf_intv
    span = z * (p * (1 - p) / d + z2 / (4 * d * d)) ** 0.5
ValueError: negative number cannot be raised to a fractional power

**Comment by chrisamiller** [comment]
This repository is a fork of the main bsmap project for convenience.  We didn't write it and no longer use it, so unfortunately can't be much help.

**Comment by ttian627** [comment]
OK, thank you!











At 2020-02-13 11:26:19, "Chris Miller" <notifications@github.com> wrote:

This repository is a fork of the main bsmap project for convenience. We didn't write it and no longer use it, so unfortunately can't be much help.
