### ISSUE TITLE
methratio.py errors

### ISSUE THREAD

**Issue by gill0110** [genome-vendor/bsmap#8]
I am trying to methratio.py  using following command line:
methratio.py -o fa1.1_methratio.txt -d Fxa.fasta  -u -p fa1.1.bam

The error pop in as:
Traceback (most recent call last):
  File "/home/jiao/miniconda2/envs/viewbs/bin/methratio.py", line 105, in <module>
    disp('loading reference file: %s ...' % options.reffile)
  File "/home/jiao/miniconda2/envs/viewbs/bin/methratio.py", line 41, in disp
    if not options.quiet: print >> sys.stderr, '[methratio] @%s \t%s' %(time.asctime(), txt)
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
view: invalid option -- 'X'

**Comment by chrisamiller** [comment]
This is not an official source for the bsmap software, just a fork that our group long ago made for convenience.  We didn't write the software and can't help with support.  Best of luck!
